### ISSUE TITLE
Roadmap to v3

### ISSUE THREAD

**Issue by jelhan** [adopted-ember-addons/ember-file-upload#306]
Lets make sure that we don't miss a breaking change that should be included in the next major release. `master` already includes breaking changes and wasn't released for days. So we should have that major rather sooner than later.

- [x] Drop support for node 8, which is EOL. #308 
- [x] Automate releases with release-it and lerna-changelog. #309 
- [ ] ~Decide on target for splat attributes (`...attributes`)~ #293
- [x] Drop support for IE 11 #319 
- [x] Rename `upload` test helper to `selectFiles` #322 
- [x] Drop support for legacy import at `<app-name>/tests/helpers/upload` #322

**Comment by gilest** [comment]
I'm getting to work on node 8 support now.

**Comment by jelhan** [comment]
Should consider dropping support for IE11 to reduce the maintenance work. Market share isn't high anymore and seems like no one wants to invest into supporting it. At least some open issues which haven't been addressed for some time.

**Comment by gilest** [comment]
### IE11

The problem for me is that it's difficult to develop and test in IE11 in my environment. If someone is willing to own it that'd be great.

### Splat attributes
From my perspective a lot of the internals of this addon are using "legacy" architecture.

As long as we can continue to provide backwards compatibility I think slowly modernising the internal code is a good idea.

In this case maybe we could rearchitect the internal component invocation by moving `ember-angle-bracket-invocation-polyfill` from devDependencies to dependencies.

There is a cost to doing this though, which is that we would be installing the polyfill in **all consuming applications**.

Looking at the polyfill docs maybe that isn't so bad:
* Supports Ember 2.12 -> 3.9
* Completely inert when running Ember 3.10 or higher

**Comment by jelhan** [comment]
> As long as we can continue to provide backwards compatibility I think slowly modernising the internal code is a good idea.
> 
> In this case maybe we could rearchitect the internal component invocation by moving `ember-angle-bracket-invocation-polyfill` from devDependencies to dependencies.

We could also consider dropping support for Ember < 3.12.

> From my perspective a lot of the internals of this addon are using "legacy" architecture.

I agree. Maybe that's simply to much for doing just now. Maybe we should release a v3 without touching that part to not block the release even longer. And then work on v4 which addresses the splat argument and other points.

**Comment by jelhan** [comment]
Another breaking change that we might want to include in v3 is renaming event handlers to `camelCase`. See #284. Not as complex as splat attributes but would align the addon more with the rest of the ecosystem.

**Comment by gilest** [comment]
Since you bought up significant API change. I'll post some of my "RFC" notes about the public APIs.

Interested to hear your thoughts. Perhaps we should create a new issue to discuss the Public API.

```handlebars
{{!-- Current 2.7 API --}}

{{#file-dropzone name="photos" as |dropzone queue|}}
  {{#if dropzone.active}}
    {{#if dropzone.valid}}
      Drop to upload
    {{else}}
      Invalid
    {{/if}}
  {{else if queue.files.length}}
    Uploading {{queue.files.length}} files. ({{queue.progress}}%)
  {{else}}
    <h4>Upload Images</h4>
    <p>
      {{#if dropzone.supported}}
        Drag and drop images onto this area to upload them or
      {{/if}}
      {{#file-upload name="photos"
                     accept="image/*"
                     multiple=true
                     onfileadd=(route-action "uploadImage")}}
        <a id="upload-image" tabindex=0>Add an Image.</a>
      {{/file-upload}}
    </p>
  {{/if}}
{{/file-dropzone}}

{{!--
  3.0/4.0? API RFC

  Contextual component

  * Attach all queue callbacks via the contextual/provider component
  * Rename FileUpload component to FileSelect, because FileUpload is too generic
  * FileSelect and FileDropzone _require_ a queue to be passed in, no more name attribute
  * Dropzone and FileSelect can only add to the queue, and provide callbacks for their own actions
  * Disadvantage: the most simple usage is a little more verbose
  * Advantage: maybe easier to use, less magic, more flexible
 --}}

<FileUploadQueue @name="photos" @onFileAdd={{action this.uploadImage}} as |queue|>
  <FileDropzone @queue={{queue}} @onDrop={{action this.filesSelected}} as |dropzone|>
    {{#if dropzone.active}}
      {{#if dropzone.valid}}
        Drop to upload
      {{else}}
        Invalid
      {{/if}}
    {{else if queue.files.length}}
      Uploading {{queue.files.length}} files. ({{queue.progress}}%)
    {{else}}
      <h4>Upload Images</h4>
      <p>
        {{#if dropzone.supported}}
          Drag and drop images onto this area to upload them or
        {{/if}}
        <FileSelect @queue={{queue}}
                    @for="upload-photo"
                    @accept="image/*"
                    @multiple={{true}}
                    @onSelected={{action this.filesSelected}}>
          <a tabindex="0">Add an Image.</a>
        </FileSelect>
      </p>
    {{/if}}
  </FileDropzone>
</FileUploadQueue>

{{!--
  Rename test helpers

  * Avoid having two helper functions called "upload"

  Mirage handler
  upload => uploadHander

  addon-test-support
  upload => selectFiles
  dragAndDrop
  dragEnter
  dragLeave
--}}
```

**Comment by gilest** [comment]
> Another breaking change that we might want to include in v3 is renaming event handlers to `camelCase`. See #284. Not as complex as splat attributes but would align the addon more with the rest of the ecosystem.

Agree this would be good, and we could do it quickly.

I added #316 where we can discuss an ideal public API for the long-term. I think a lot of new users struggle with the existing API.

**Comment by jelhan** [comment]
I like the idea of refactoring the public API. But maybe that's more for a v4 as it still requires a lot of work and we should not delay the v3 even more. To reduce the upgrade costs we should batch all changes to the public template API in one major version. That would include the splat attributes topic and the renaming of actions to `camelCase`.

The only change I would include in v3 is the renaming of `upload` test helper to `selectFiles`. `master` already contains a breaking change of it's public API. So it makes sense to have the rename in the same go.

**Comment by gilest** [comment]
> The only change I would include in v3 is the renaming of `upload` test helper to `selectFiles`. `master` already contains a breaking change of it's public API. So it makes sense to have the rename in the same go.

Seems sensible to me, would you like me to stage a PR with this change?

**Comment by jelhan** [comment]
> Seems sensible to me, would you like me to stage a PR with this change?

That would be awesome.

**Comment by gilest** [comment]
All looking good @jelhan – I'll let you merge #319 whenever you're ready 😄

**Comment by gilest** [comment]
V3 has been released. Compiled remaining PRs and issues into #331
