### ISSUE TITLE
Roadmap to v5

### ISSUE THREAD

**Issue by gilest** [adopted-ember-addons/ember-file-upload#331]
Since v3 has been released. I've compiled a list of outstanding PRs and issues.

### Target v4

- [x] Drop support for Ember 2 #430
- [x] Update ember-cli #430
- [x] Rename all events to camelCase #476
- [x] Change `File.progress` value from `NaN` to `null` if total file size is unknown (`ProgressEvent.total === 0`) #344 (PR #475)

### Target v5

- [x] Decide on target for splat attributes (...attributes) #293
- [x] Upgrade to glimmer components and native classes #514
- [x] Update docs examples to use Octane syntax #522
- [x] Remove validation support #397 
- [x] Remove deprecated events #583
- [ ] File.upload() should resolve with a Reponse object #546
- [x] Reconsider HTML markup to meet accessibility standards #374 #387 #388 #316 #620
- [x] Improve public API #316
  - [x] file-queue helper #620
  - [x] Use a custom modifier to register/unregister events and drop `@ember/render-modifiers` as a dependency #654
  - [x] FileUpload component #620
  - [x] FileDropzone component #678
  - [x] #679 – implemented in #678
  - [x] #701
  - [x] Register deprecations #706
- [x] Update docs #721
- [x] Update support matrix in README #721
- [x] Add Upgrading to v5 guide #723
- [x] New Documentation site #642
- [ ] Improve test-support #641

**Comment by LuisAverhoff** [comment]
Would it possible to add issue #201 to the list? This issue makes using drag and drop a pain because of the constant flickering.

**Comment by jelhan** [comment]
> Would you consider adding issue #201 to the list?

Do you expect a breaking change to be required for a fix? Haven't had a investigated the issue yet. But from reading the description it doesn't sound like it requires a change in public API to be fixed.

Actually adding or not adding to this list doesn't make a difference if it's fixed or not. That only depends on a person picking up that task. 😉

**Comment by gilest** [comment]
@jelhan I've updated the roadmap to push major API and Octane updates to v5.

Suggest we merge what we can from open PRs now and then release v4 (believe you are the only contributor who can release).

Let me know your thoughts 🙇

**Comment by gilest** [comment]
@jelhan I'm happy for you to release `4.0.0` now 🙌

**Comment by jelhan** [comment]
> @jelhan I'm happy for you to release `4.0.0` now raised_hands

I just [released v4.0.0](https://github.com/adopted-ember-addons/ember-file-upload/releases/tag/v4.0.0). Thanks a lot for all your work that got in!

> believe you are the only contributor who can release

To be honest I thought you have NPM permissions as well. Maybe we should ask someone with the required permissions to add you as well?

**Comment by jelhan** [comment]
@gilest Do you want to announce the release on Twitter and Ember's Discord as you have done most of the work? Maybe we should wait with announcing until we fixed the docs deployment (https://github.com/adopted-ember-addons/ember-file-upload/pull/429#issuecomment-864902816)?

**Comment by gilest** [comment]
v5 has been released. Remaining items ported to #755
