### ISSUE TITLE
v6 Roadmap

### ISSUE THREAD

**Issue by gilest** [adopted-ember-addons/ember-file-upload#755]
### Target v6

- [x] File.upload() should resolve with a Reponse object #546
- [x]  #767
- [x] Remove all `until: 6.0` deprecations #779
- [x] Drop support for Node 12 #780
  - [x] Upgrade `tracked-built-ins` to v3

**Comment by bertdeblock** [comment]
What do you think about dropping support for `ember-modifier` v2?
New deprecations were introduced in v3.2 (see #764) and resolving those isn't super straight forward when you still want to support v2. You'd have to use macros to conditionally include the correct modifier code.

**Comment by gilest** [comment]
@bertdeblock Yes I've been seeing the warnings. I think that's a good idea – thanks.

**Comment by bertdeblock** [comment]
We could also drop support for Node v12? That way we can also e.g. update `tracked-built-ins` to v3.
