### ISSUE TITLE
v7 Roadmap

### ISSUE THREAD

**Issue by gilest** [adopted-ember-addons/ember-file-upload#783]
### Target v7
- [x] v2 addon format #800
- [x] Extract mirage handler into new `ember-file-upload-mirage` package #802
- [x] Named export all modules from `ember-file-upload` #803
- [x] Document upgrading to v7 #805
