### ISSUE TITLE
Publish Glint types

### ISSUE THREAD

**Issue by gilest** [adopted-ember-addons/ember-file-upload#965]
- [x] Set up Glint in addon and declare Glint-compatible types (#964)
- [x] Configure separate declaration directory (https://github.com/adopted-ember-addons/ember-file-upload/pull/966)
- [x] Set up Glint in test-app and consume/check addon types (#969)
- [x] Document Glint configuration for addon consumers (#972)
